name: create tag and release

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH: main

permissions:
  contents: write

jobs:
  # create tag and draft release
  create_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # create YYYYMMDDhhmm string for tag and release
      - name: Get timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M')" >> "$GITHUB_ENV"

      # create tag and push
      - name: Create tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git tag -a $timestamp -m "$timestamp"
          git push origin $timestamp

      # create draft release based on tag
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.timestamp }}
          draft: true