name: create tag and release

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH: main

permissions:
  actions: write

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      branch-is-default: ${{ env.is_default_branch }}

    # Check if the branch is $DEFAULT_BRANCH. A bit fuzzy because ref_type is not checked.
    steps:
      - name: show message in case the branch is not $DEFAULT_BRANCH
        if: ${{ github.ref_name != env.DEFAULT_BRANCH }}
        run: echo "The branch is not '${DEFAULT_BRANCH}'."
      - name: set a context to pass to another job
        if: ${{ github.ref_name == env.DEFAULT_BRANCH }}
        run: |
          echo "The branch is '${DEFAULT_BRANCH}'.";
          echo "is_default_branch=true" >> $GITHUB_ENV

  # create YYYYMMDDhhmm string for tag 
  get_timestamp:
    runs-on: ubuntu-latest
    needs: set_git_identity
    outputs:
      timestamp: ${{ steps.set_timestamp.outputs.timestamp }}
    steps:
      - name: Set timestamp
        id: set_timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M')"
  
  # create tag
  create_tag:
    runs-on: ubuntu-latest
    needs: get_timestamp
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag -a ${{ needs.get_timestamp.outputs.timestamp }} -m "${{ needs.get_timestamp.outputs.timestamp }}"
          git push origin ${{ needs.get_timestamp.outputs.timestamp }}

  # create release
  create_release_draft:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          files: ''
          tag_name: ${{ needs.get_timestamp.outputs.timestamp }}
          draft: true
