name: create tag and release

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH: main

jobs:
  # create tag and draft release
  create_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # create YYYYMMDDhhmm string for tag and release
      - name: Get timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M')" >> "$GITHUB_ENV"

      # create tag and draft release
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.timestamp }}
          tag_name: ${{ env.timestamp }}
          draft: true
          generate_release_notes: true