name: create tag and release

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH: main

permissions:
  contents: write

jobs:
  # create YYYYMMDDhhmm string for tag 
  get_timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.set_timestamp.outputs.timestamp }}
    steps:
      - name: Set timestamp
        id: set_timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M')"
  
  # create tag
  create_tag:
    runs-on: ubuntu-latest
    needs: get_timestamp
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create tag
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@users.noreply.github.com"
          git tag -a ${{ needs.get_timestamp.outputs.timestamp }} -m "${{ needs.get_timestamp.outputs.timestamp }}"
          git push origin ${{ needs.get_timestamp.outputs.timestamp }}

  # create release
  create_release_draft:
    runs-on: ubuntu-latest
    needs: [create_tag, get_timestamp]
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          files: ''
          tag_name: ${{ needs.get_timestamp.outputs.timestamp }}
          draft: true
