name: create tag and release

on:
  workflow_dispatch:

env:
  DEFAULT_BRANCH: main

permissions:
  contents: write

jobs:
  # create YYYYMMDDhhmm string for tag 
  get_timestamp:
    runs-on: ubuntu-latest
    id: get_timestamp
    steps:
      - name: Get timestamp
        run: echo "$(date +'%Y%m%d%H%M')"

      - name: Set timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"
  
  # create tag
  create_tag:
    runs-on: ubuntu-latest
    needs: get_timestamp
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git tag -a ${{ steps.get_timestamp.outputs.timestamp }} -m "${{ steps.get_timestamp.outputs.timestamp }}"
          git push origin ${{ steps.get_timestamp.outputs.timestamp }}

  # create release
  create_release_draft:
    runs-on: ubuntu-latest
    needs: create_tag
    steps:
      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_timestamp.outputs.timestamp }}
          draft: true
